import type { SessionWarning } from '@spiderbyte/protocol';
import type { ActivateSkillPayload, ActivatePluginCommandPayload, AddAdditionalDirPayload, AddAdditionalDirResult, BeginCompactionPayload, CancelPayload, CancelPlanPayload, CancelShellCommandPayload, CreateGoalPayload, DetachBackgroundPayload, EmptyPayload, EnterSwarmPayload, GetBackgroundOutputPayload, GetBackgroundPayload, ImportContextPayload, McpServerInfo, McpStartupMetrics, PromptPayload, RunShellCommandPayload, ReconnectMcpServerPayload, RenameSessionPayload, RegisterToolPayload, SessionAPI, SetActiveToolsPayload, SetModelPayload, SetPermissionPayload, SetThinkingPayload, SkillSummary, PluginCommandDef, SteerPayload, StopBackgroundPayload, UndoHistoryPayload, UnregisterToolPayload, UpdateSessionMetadataPayload } from '#/rpc';
import type { PromisableMethods } from '#/utils/types';
import type { Session, SessionMeta } from '.';
type AgentScopedPayload<T> = T & {
    agentId: string;
};
export declare class SessionAPIImpl implements PromisableMethods<SessionAPI> {
    protected readonly session: Session;
    constructor(session: Session);
    renameSession(payload: RenameSessionPayload): Promise<void>;
    updateSessionMetadata(payload: UpdateSessionMetadataPayload): Promise<void>;
    getSessionMetadata(_payload: EmptyPayload): SessionMeta;
    listSkills(_payload: EmptyPayload): Promise<readonly SkillSummary[]>;
    listPluginCommands(_payload: EmptyPayload): readonly PluginCommandDef[];
    listMcpServers(_payload: EmptyPayload): readonly McpServerInfo[];
    getMcpStartupMetrics(_payload: EmptyPayload): Promise<McpStartupMetrics>;
    reconnectMcpServer(payload: ReconnectMcpServerPayload): Promise<void>;
    generateAgentsMd(_payload: EmptyPayload): Promise<void>;
    getSessionWarnings(_payload: EmptyPayload): Promise<readonly SessionWarning[]>;
    waitForBackgroundTasksOnPrint(_payload: EmptyPayload): Promise<void>;
    handlePrintMainTurnCompleted(_payload: EmptyPayload): Promise<'finish' | 'continue'>;
    addAdditionalDir(payload: AddAdditionalDirPayload): Promise<AddAdditionalDirResult>;
    prompt({ agentId, ...payload }: AgentScopedPayload<PromptPayload>): Promise<void>;
    steer({ agentId, ...payload }: AgentScopedPayload<SteerPayload>): Promise<void>;
    runShellCommand({ agentId, ...payload }: AgentScopedPayload<RunShellCommandPayload>): Promise<import("#/rpc").ShellCommandResult>;
    cancelShellCommand({ agentId, ...payload }: AgentScopedPayload<CancelShellCommandPayload>): Promise<void>;
    cancel({ agentId, ...payload }: AgentScopedPayload<CancelPayload>): Promise<void>;
    undoHistory({ agentId, ...payload }: AgentScopedPayload<UndoHistoryPayload>): Promise<void>;
    setModel({ agentId, ...payload }: AgentScopedPayload<SetModelPayload>): Promise<import("#/rpc").SetModelResult>;
    setThinking({ agentId, ...payload }: AgentScopedPayload<SetThinkingPayload>): Promise<void>;
    setPermission({ agentId, ...payload }: AgentScopedPayload<SetPermissionPayload>): Promise<void>;
    getModel({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<string>;
    enterPlan({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<void>;
    cancelPlan({ agentId, ...payload }: AgentScopedPayload<CancelPlanPayload>): Promise<void>;
    clearPlan({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<void>;
    enterSwarm({ agentId, ...payload }: AgentScopedPayload<EnterSwarmPayload>): Promise<void>;
    exitSwarm({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<void>;
    getSwarmMode({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<boolean>;
    beginCompaction({ agentId, ...payload }: AgentScopedPayload<BeginCompactionPayload>): Promise<void>;
    cancelCompaction({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<void>;
    registerTool({ agentId, ...payload }: AgentScopedPayload<RegisterToolPayload>): Promise<void>;
    unregisterTool({ agentId, ...payload }: AgentScopedPayload<UnregisterToolPayload>): Promise<void>;
    setActiveTools({ agentId, ...payload }: AgentScopedPayload<SetActiveToolsPayload>): Promise<void>;
    stopBackground({ agentId, ...payload }: AgentScopedPayload<StopBackgroundPayload>): Promise<void>;
    detachBackground({ agentId, ...payload }: AgentScopedPayload<DetachBackgroundPayload>): Promise<import("..").BackgroundTaskInfo | undefined>;
    clearContext({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<void>;
    importContext({ agentId, ...payload }: AgentScopedPayload<ImportContextPayload>): Promise<void>;
    activateSkill({ agentId, ...payload }: AgentScopedPayload<ActivateSkillPayload>): Promise<void>;
    activatePluginCommand({ agentId, ...payload }: AgentScopedPayload<ActivatePluginCommandPayload>): Promise<void>;
    startBtw({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<string>;
    createGoal({ agentId, ...payload }: AgentScopedPayload<CreateGoalPayload>): Promise<import("#/rpc").GoalSnapshot>;
    getGoal({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("#/rpc").GoalToolResult>;
    pauseGoal({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("#/rpc").GoalSnapshot>;
    resumeGoal({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("#/rpc").GoalSnapshot>;
    cancelGoal({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("#/rpc").GoalSnapshot>;
    getCronTasks({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("#/rpc").GetCronTasksResult>;
    getBackgroundOutput({ agentId, ...payload }: AgentScopedPayload<GetBackgroundOutputPayload>): Promise<string>;
    getContext({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("..").AgentContextData>;
    getConfig({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("../agent/config").AgentConfigData>;
    getPermission({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("../agent/permission").PermissionData>;
    getPlan({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<import("../agent/plan").PlanData>;
    getUsage({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<any>;
    getTools({ agentId, ...payload }: AgentScopedPayload<EmptyPayload>): Promise<readonly import("..").ToolInfo[]>;
    getBackground({ agentId, ...payload }: AgentScopedPayload<GetBackgroundPayload>): Promise<readonly import("..").BackgroundTaskInfo[]>;
    private getAgent;
    private needUpdateEasyTitle;
    private updatePromptMetadata;
}
export {};
