/**
 * Public platform-contract surface for klient.
 *
 * The schemas are re-exported from `@moonshot-ai/protocol` rather than
 * mirrored here. This keeps protocol the single wire-contract authority while
 * allowing klient consumers to use the same validation vocabulary as the
 * transport-agnostic facade.
 */
export {
  agentSessionIdSchema,
  agentSessionSchema,
  artifactIdSchema,
  artifactKindSchema,
  artifactRefSchema,
  artifactSchema,
  capabilitySchema,
  executionTargetIdSchema,
  executionTargetLocalitySchema,
  executionTargetSchema,
  executionTargetStateSchema,
  executionTargetTypeSchema,
  platformActorSchema,
  platformCommandAcceptedSchema,
  platformEntityTypeSchema,
  platformIdentifierSchema,
  platformLifecycleEventSchema,
  platformLifecycleEventTypeSchema,
  platformMetadataSchema,
  platformWorkspaceSchema,
  policyDecisionIdSchema,
  policyDecisionOutcomeSchema,
  policyDecisionSchema,
  policyDecisionStateSchema,
  providerConnectionIdSchema,
  providerConnectionProviderSchema,
  providerConnectionSchema,
  providerConnectionScopeSchema,
  providerConnectionStateSchema,
  resourceIdSchema,
  resourceRefSchema,
  resourceSchema,
  resourceStateSchema,
  resourceTypeSchema,
  runIdSchema,
  runPlanStepSchema,
  runPlanStepStatusSchema,
  runSchema,
  runStatusSchema,
  usageMeterSchema,
  usageRecordIdSchema,
  usageRecordSchema,
  usageUnitSchema,
  workspaceIdSchema,
  workspaceLifecycleStateSchema,
} from '@moonshot-ai/protocol';

export type {
  AgentSession,
  AgentSessionId,
  AgentSessionState,
  Artifact,
  ArtifactId,
  ArtifactKind,
  ArtifactRef,
  Capability,
  ExecutionTarget,
  ExecutionTargetId,
  ExecutionTargetLocality,
  ExecutionTargetState,
  ExecutionTargetType,
  PlatformActor,
  PlatformCommandAccepted,
  PlatformEntityType,
  PlatformIdentifier,
  PlatformLifecycleEvent,
  PlatformWorkspace,
  PolicyDecision,
  PolicyDecisionId,
  PolicyDecisionOutcome,
  PolicyDecisionState,
  ProviderConnection,
  ProviderConnectionId,
  ProviderConnectionProvider,
  ProviderConnectionState,
  Resource,
  ResourceId,
  ResourceRef,
  ResourceState,
  ResourceType,
  Run,
  RunId,
  RunPlanStep,
  RunStatus,
  UsageMeter,
  UsageRecord,
  UsageRecordId,
  UsageUnit,
  WorkspaceId,
  WorkspaceLifecycleState,
} from '@moonshot-ai/protocol';
